---
apiVersion: v1
kind: Service
metadata:
  name: springapp
  labels:
    run: springapp
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: springapp
