---
apiVersion: v1
kind: Service
metadata:
  name: springapp
  labels:
    run: springapp
spec:
  type: LoadBalancer
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
    name: http
  selector:
    run: springapp
