---
apiVersion: v1
kind: Service
metadata:
  name: springapp
  labels:
    run: springapp
spec:
  type: LoadBalancer
  selector:
    run: springapp
  ports:
    - name: http
      port: 35000
      targetPort: 8080
      protocol: TCP
